### ISSUE TITLE
TOB Search and UI Use Cases we want to support

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#406]
In TOB the Credentials are loaded into the TOB Search database using an Issuer-defined mapping from whatever Credential they are Issuing. The Credentials are map into a pretty constrained database model that enables search - credentials, credential types, topics, names, address, people and contacts. Once there we have several use cases in searching that we want to support. The use cases are described here.

## Independent or Linked

The two main approaches for search and presentation are Independent (aka the Ontario model) and linked (aka the BC model). 

In the independent approach search results and data presentation is at the topic level and relationships between topics (e.g. parent-child, legal entity-dba, etc.) are ignored. So, although the data is stored with links between topics that make up different segments of a larger organizational entity, those links are ignored from a search and presentation perspective.

In the linked approach, search results (sort of) and data presentation is at the organizational level and all linked topics are found together, regardless of which topic was found by the search.

So - given a legal entity "ABC Inc." and two child (DBA) entities "ABC Store1" and "ABC Store2", the data would be stored the same whether regardless of the Search/Presentation approach.

- Search for "ABC"
   - Returns three results for "independent" - one for each topic - with no linkage between the three
   - Returns one result ("ABC Inc") for linked - each topic is found and linked to the parent
- Search for "Store1"
   - Returns one result for "independent" - the "ABC Store1" topic - no linkage to the "ABC Inc." topic
   - Returns one result ("ABC Inc") for linked - the one topic is found and the linked followed to the parent

There are two caveats to this:

- From a usability perspective, the second example is weird for the "linked" use case.  The user would wonder why "ABC Inc." is showing up for a search of "Store1"?  So, we might actually want the linked search to return the matched topics AND the parent, so the UI can show why the parent was matched.  Perhaps the search results for the linked case needs to include both the "parent" record (since that's what we will drill into) and any "child" records that matched the search criteria. 
   - Or, perhaps the search results should just return the found topics (same as independent), but that the "drill down" API should return always the linked topics, starting with the parent.
   - May result in a weird UI experience though - why am I drilling into "ABC Inc." when I wanted "ABC Store1"?  
   - Perhaps drill down goes to the "ABC Store1" page, with a link up to the parent - "ABC Inc.".

- If the search is made the same for the independent and linked cases, and we are using the independent approach, we have to be sure that the relationships between the linked topics are NOT exposed in the browser.  In other words, we can't just send the data to the frontend with the relationships defined and have the frontend deal with it.  That would expose in JSON the data we want hidden.

**Comment by nrempel** [comment]
What I propose for the UX challenges listed in `caveats` is:

similar to

> Or, perhaps the search results should just return the found topics (same as independent), but that the "drill down" API should return always the linked topics, starting with the parent.

I propose the search results are always the "independent" case. So a search for "ABC" would return 3 results and a search for "Store1" would only return 1 result in all cases.

This makes for a clear user experience but also keeps things consistent on the backend.

Then, in the topic details page:

The independent case:

Would not show any linkage at all.

In the linked case:

Links and information for both parent and children will be provided.

So, a user would need to click twice to reach a DBA's parent but I think it would be much less confusing.

All endpoints that enable the browser to query for related topics will be added via the `custom_settings` mechanism so that the Ontario deployment can keep them turned off to ensure it is not possible to query for relationships.

---

Let me know what you think of this approach @swcurran.

**Comment by mitovskaol** [comment]
I like this approach, it is cleaner this way,  more straightforward for the user, and give the UI control over when to fetch the related records (lazy fetching) if they are required at all (not for Ontario).
Just to confirm - for Ontario, the API will NOT return the related records even if a request for them is received because the Ontario's custom_settings will explicitly have the relationships turned off?

**Comment by swcurran** [comment]
Agree that this captures what we discussed most recently and hits the mark - getting rid of the awkward UI for BC and making it easy for both BC and Ontario to use the search and display APIs.  Nice!

**Comment by nrempel** [comment]
👍🏼

Just an FYI: I'm going to track the effort to move related topic endpoints to custom_settings here: #433.

This way, I can release this work and unblock Ian and Ivan.
